# Auto-generated by inspect_hf_models.py
# Paste these classes into client/fl_client.py and verify
# layer names match your state_dict keys exactly.

import torch.nn as nn

# ── COVID ──
class CovidCNN(nn.Module):
    # Auto-generated from state_dict -- verify layer names match exactly
    def __init__(self, num_classes=3):
        super().__init__()
        self.classifier = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(),
            nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(),
            nn.Conv2d(64, 128, 3, padding=1), nn.ReLU(),
            nn.Conv2d(128, 256, 3, padding=1), nn.ReLU(),
            nn.Linear(50176, 128), nn.ReLU(),
            nn.Linear(128, 3),
        )
        # NOTE: update _flat_size if your input is not 224x224
        # After pooling, spatial dim depends on MaxPool count

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        return self.classifier(x)
